FROM node:24-slim AS web-build

WORKDIR /web
COPY web/package*.json /web/
RUN npm ci
COPY web /web
ARG VITE_BASE_PATH=/web/
ARG VITE_POSTBRIDGE_APP_MODE=selfhost
ARG VITE_YANDEX_METRIKA_COUNTER_ID=
ARG VITE_TELEGRAM_BOT_NAME=
ARG VITE_MAX_BOT_URL=
ARG VITE_BILLING_SUPPORT_EMAIL=
ENV VITE_BASE_PATH=${VITE_BASE_PATH}
ENV VITE_POSTBRIDGE_APP_MODE=${VITE_POSTBRIDGE_APP_MODE}
ENV VITE_YANDEX_METRIKA_COUNTER_ID=${VITE_YANDEX_METRIKA_COUNTER_ID}
ENV VITE_TELEGRAM_BOT_NAME=${VITE_TELEGRAM_BOT_NAME}
ENV VITE_MAX_BOT_URL=${VITE_MAX_BOT_URL}
ENV VITE_BILLING_SUPPORT_EMAIL=${VITE_BILLING_SUPPORT_EMAIL}
RUN npm run build

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml README.md alembic.ini /app/
COPY src /app/src
COPY alembic /app/alembic
COPY --from=web-build /web/dist /app/web/dist

RUN pip install --no-cache-dir .

EXPOSE 8000
