#!/usr/bin/env python3
"""Generate a local self-host .env file with persistent random bootstrap secrets."""

from __future__ import annotations

import argparse
import base64
from pathlib import Path
import secrets


def _fernet_key() -> str:
    return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("ascii")


def _token() -> str:
    return secrets.token_urlsafe(32)


def _env_text() -> str:
    postgres_password = _token()
    credentials_key = _fernet_key()
    service_token = _token()
    database_url = (
        "postgresql+psycopg2://postbridge:"
        f"{postgres_password}@postgres:5432/postbridge"
    )
    return f"""# Generated by scripts/init_self_host_env.py.
# Keep this file private. Do not commit it.

APP_ENV=dev
POSTBRIDGE_APP_MODE=selfhost
POSTBRIDGE_SELFHOST_TENANT_ID=00000000-0000-4000-8000-000000000001
POSTBRIDGE_DEFAULT_LOCALE=en
POSTBRIDGE_DEFAULT_TIMEZONE=UTC

POSTGRES_PASSWORD={postgres_password}
DATABASE_URL={database_url}
REDIS_URL=redis://redis:6379/0
CELERY_TASK_ALWAYS_EAGER=0

CREDENTIALS_ENCRYPTION_KEY={credentials_key}

# Optional trusted server-to-server API token. The browser never uses this.
CORE_SERVICE_TOKEN={service_token}

# Optional integrations can be configured in the first-run wizard when needed immediately.
# Keep env values empty unless you intentionally want an install-wide fallback.
TELEGRAM_API_ID=
TELEGRAM_API_HASH=
TELEGRAM_SESSION_NAME=postbridge
TELEGRAM_SESSION_STRING=
TELEGRAM_PROXY_URL=
TELEGRAM_PROXY_FALLBACK_DIRECT=false

MAX_API_BASE_URL=
MAX_API_TOKEN=
MAX_API_TIMEOUT_SECONDS=30

VK_ACCESS_TOKEN=
VK_USER_ACCESS_TOKEN=

LINKEDIN_ACCESS_TOKEN=
LINKEDIN_AUTHOR_URN=
LINKEDIN_API_VERSION=202601

TELEGRAM_BOT_TOKEN=
TELEGRAM_BOT_USERNAME=
BOT_MODE=long_polling
BOT_BACKEND=core_db
CORE_BASE_URL=http://127.0.0.1:8000
WEB_APP_BASE_URL=http://127.0.0.1:8000/web
BOT_WEBHOOK_BASE_URL=
BOT_WEBHOOK_PATH=/internal/bot/webhook
BOT_WEBHOOK_SECRET=

AI_GATEWAY_ENABLED=0
AI_GATEWAY_BASE_URL=
AI_GATEWAY_API_KEY=
AI_GATEWAY_TIMEOUT_SECONDS=300
AI_GATEWAY_DEFAULT_MODEL=
AI_GATEWAY_DEFAULT_RESPONSE_LANGUAGE=en
AI_IMAGE_GENERATION_MODEL=
AI_IMAGE_GENERATION_TIMEOUT_SECONDS=300
AI_IMAGE_GENERATION_SIZE=1536x1024

AGENT_LLM_BASE_URL=
AGENT_LLM_API_KEY=
AGENT_LLM_DEFAULT_MODEL=
AGENT_LLM_EMBEDDING_MODEL=text-embedding-3-small
AGENT_LLM_MAX_TOKENS=2048
AGENT_DEFAULT_RESPONSE_LANGUAGE=en
AGENT_SEARCH_BACKENDS=searxng,duckduckgo
AGENT_SEARCH_SEARXNG_BASE_URL=
AGENT_SEARCH_LANGUAGE=en

MEDIA_STORAGE_TYPE=none
MEDIA_STORAGE_PATH=
MEDIA_BASE_URL=
S3_ENDPOINT_URL=
S3_REGION=us-east-1
S3_BUCKET=
S3_ACCESS_KEY=
S3_SECRET_KEY=
S3_PUBLIC_BASE_URL=

STATUS_EVENT_WEBHOOK_URL=
STATUS_EVENT_WEBHOOK_TOKEN=
STATUS_EVENT_WEBHOOK_TIMEOUT_SECONDS=5
SYNC_PUBLISH_TOKEN=
SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.1
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a local self-host .env file.")
    parser.add_argument("--output", default=".env", help="Path to write. Default: .env")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing file.")
    args = parser.parse_args()

    path = Path(args.output)
    if path.exists() and not args.force:
        print(f"{path} already exists; leaving it unchanged. Use --force to overwrite.")
        return 0

    path.write_text(_env_text(), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    print(f"Generated {path} with local random bootstrap secrets.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
